//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OopTranslation.I18n {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IoFileDialogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IoFileDialogs() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OopTranslation.IoFileDialogs", typeof(IoFileDialogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CancelButtonText.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContentViewMode.
        /// </summary>
        public static string ContentViewMode {
            get {
                return ResourceManager.GetString("ContentViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuAddNetworkPlaceCommandText.
        /// </summary>
        public static string ContextMenuAddNetworkPlaceCommandText {
            get {
                return ResourceManager.GetString("ContextMenuAddNetworkPlaceCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuCollapseCommandText.
        /// </summary>
        public static string ContextMenuCollapseCommandText {
            get {
                return ResourceManager.GetString("ContextMenuCollapseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuConnectNetworkDriveCommandText.
        /// </summary>
        public static string ContextMenuConnectNetworkDriveCommandText {
            get {
                return ResourceManager.GetString("ContextMenuConnectNetworkDriveCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuCopyCommandText.
        /// </summary>
        public static string ContextMenuCopyCommandText {
            get {
                return ResourceManager.GetString("ContextMenuCopyCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuCutCommandText.
        /// </summary>
        public static string ContextMenuCutCommandText {
            get {
                return ResourceManager.GetString("ContextMenuCutCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuDeleteCommandText.
        /// </summary>
        public static string ContextMenuDeleteCommandText {
            get {
                return ResourceManager.GetString("ContextMenuDeleteCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuDisconnectNetworkDriveCommandText.
        /// </summary>
        public static string ContextMenuDisconnectNetworkDriveCommandText {
            get {
                return ResourceManager.GetString("ContextMenuDisconnectNetworkDriveCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuDisplaySettingsCommandText.
        /// </summary>
        public static string ContextMenuDisplaySettingsCommandText {
            get {
                return ResourceManager.GetString("ContextMenuDisplaySettingsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuEditCommandText.
        /// </summary>
        public static string ContextMenuEditCommandText {
            get {
                return ResourceManager.GetString("ContextMenuEditCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuEjectCommandText.
        /// </summary>
        public static string ContextMenuEjectCommandText {
            get {
                return ResourceManager.GetString("ContextMenuEjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuExpandCommandText.
        /// </summary>
        public static string ContextMenuExpandCommandText {
            get {
                return ResourceManager.GetString("ContextMenuExpandCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuExtractCommandText.
        /// </summary>
        public static string ContextMenuExtractCommandText {
            get {
                return ResourceManager.GetString("ContextMenuExtractCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuFormatCommandText.
        /// </summary>
        public static string ContextMenuFormatCommandText {
            get {
                return ResourceManager.GetString("ContextMenuFormatCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuLinkCommandText.
        /// </summary>
        public static string ContextMenuLinkCommandText {
            get {
                return ResourceManager.GetString("ContextMenuLinkCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuManageCommandText.
        /// </summary>
        public static string ContextMenuManageCommandText {
            get {
                return ResourceManager.GetString("ContextMenuManageCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuOpenAsCommandText.
        /// </summary>
        public static string ContextMenuOpenAsCommandText {
            get {
                return ResourceManager.GetString("ContextMenuOpenAsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ContextMenuOpenCommandText.
        /// </summary>
        public static string ContextMenuOpenCommandText {
            get {
                return ResourceManager.GetString("ContextMenuOpenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DetailsView_DateModifiedColumnCaption.
        /// </summary>
        public static string DetailsView_DateModifiedColumnCaption {
            get {
                return ResourceManager.GetString("DetailsView_DateModifiedColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DetailsView_NameColumnCaption.
        /// </summary>
        public static string DetailsView_NameColumnCaption {
            get {
                return ResourceManager.GetString("DetailsView_NameColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DetailsView_SizeColumnCaption.
        /// </summary>
        public static string DetailsView_SizeColumnCaption {
            get {
                return ResourceManager.GetString("DetailsView_SizeColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DetailsView_TypeColumnCaption.
        /// </summary>
        public static string DetailsView_TypeColumnCaption {
            get {
                return ResourceManager.GetString("DetailsView_TypeColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DetailsViewMode.
        /// </summary>
        public static string DetailsViewMode {
            get {
                return ResourceManager.GetString("DetailsViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ExtraLargeViewMode.
        /// </summary>
        public static string ExtraLargeViewMode {
            get {
                return ResourceManager.GetString("ExtraLargeViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FileNameLabelText.
        /// </summary>
        public static string FileNameLabelText {
            get {
                return ResourceManager.GetString("FileNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LargeViewMode.
        /// </summary>
        public static string LargeViewMode {
            get {
                return ResourceManager.GetString("LargeViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ListViewMode.
        /// </summary>
        public static string ListViewMode {
            get {
                return ResourceManager.GetString("ListViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MediumViewMode.
        /// </summary>
        public static string MediumViewMode {
            get {
                return ResourceManager.GetString("MediumViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NewFolderButtonText.
        /// </summary>
        public static string NewFolderButtonText {
            get {
                return ResourceManager.GetString("NewFolderButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OpenFileDialogOkButtonText.
        /// </summary>
        public static string OpenFileDialogOkButtonText {
            get {
                return ResourceManager.GetString("OpenFileDialogOkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SmallViewMode.
        /// </summary>
        public static string SmallViewMode {
            get {
                return ResourceManager.GetString("SmallViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TilesViewMode.
        /// </summary>
        public static string TilesViewMode {
            get {
                return ResourceManager.GetString("TilesViewMode", resourceCulture);
            }
        }
    }
}
